Rfc 18 application process
internet-sicherheit/eco-blockchain-governance pull request #42
Opened 2020-09-04 09:57 UTC by beeshot

@chinmay241 and I worked that out. Happy to get feedback.

2020-09-04 11:00 UTC, kiview requested changes

2020-09-04 11:08 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
Yes, the formal ones the requirements that need to be fulfilled to apply. This is how to evaluate them and compare them.

2020-09-04 11:09 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +* Nods(s) that are implemented after successful application
Nodes, so while applying it should be clear what exactly they are applying for e.g. Validator Node vs. Node without writing permission

2020-09-04 11:10 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +* Transparency degree of process e.g. publication on website
Transparency over the process and requirements. But the other option could be relevant as well

2020-09-04 11:11 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +* Interval for internal voting process
Bloxberg is an example

2020-09-04 11:14 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +* What alternative voting systems could be used?
To the the one implemented by bloxberg, basically what mechanisms should be defined to emerge towards consensus in an application process.

2020-09-04 11:22 UTC, kiview commented on governance/0018-application-process/rfc-18.md
> +* Nods(s) that are implemented after successful application
This is a technical detail, however.  So the question is, for which kind of membership does one apply (with the set of different membership classes being up to the implementation, e.g. Steward, Associated Member, Commercial Sponsor, etc.)? 

In many networks, being a member means operating a node, but e.g. bloxberg is talking about how to cater for a membership model, that allows members to join the consortium without the capabilities to operate a validator node.

2020-09-04 11:29 UTC, kiview commented on governance/0018-application-process/rfc-18.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
However, this RFC does not (yet) specify how to evaluate and to weight the criteria outlined in RFC-0003. 

So the question is, what information goes into the decision process (as a subprocess of the application process) and what is the outcome of the decision (and if this is part of this RFC). 

A basic model would use criteria as implemented in a RFC-0003 as a binary quality gate, leading to 1 (application approved) or 0 (application dismissed). Bloxberg has a binary value (is a member an academic research organisation), however, it is evaluated by the members in a fuzzy-logic kind of way (a person is responsible to decide) and therefore the fuzziness is seemingly countered by using a majority vote.

Where does this leave us now? Maybe this hints at the indication, that we should more clearly formulate the required existence of artifacts such as a decisions process, weight functions, etc. as part of the specification.

2020-09-04 11:31 UTC, kiview commented on governance/0018-application-process/rfc-18.md
> +* Interval for internal voting process
This is true, however, by adding this point to the specification, it becomes a requirement for all implementation (and Sovrin does not perform interval voting).

Though particularly, my comment here was about `internal voting` lacking the definition in the context of the RFC. E.g. internal voting can mean voting as part of the decision process of the application process.

2020-09-04 11:31 UTC, kiview commented on governance/0018-application-process/rfc-18.md
> +* What alternative voting systems could be used?
But this RFC does not specify the bloxberg voting mechanism, so alternative can just be in reference to the specification section.

2020-09-04 14:37 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +* Interval for internal voting process
This was more meant as a question if internal voting should happen or not. Hence it should be discussed, As an example there is bloxberg and us an unresolved question if such a voting process really makes sense.

2020-09-04 14:43 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +* Nods(s) that are implemented after successful application
Yes, this it what this implies. Can be also formulated differently. Versions of Memberships and requirements for operating node?

2020-09-07 09:35 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
how about we make it another RFC, if internal voting is considered, where weight functions, artifacts etc. described in more details. Other we add to this document.

2020-09-07 09:58 UTC, kiview commented on governance/0018-application-process/rfc-18.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
Meaning this RFC does not handle the evaluation of the criteria as part of the applications process as implemented by an RFC-0003 implementation, correct? Actually, this RFC can have a point which is exactly this `Evaluation of applicants eligibility criteria as implemented by RFC-0003 implementation`. This is sufficiently abstract.

2020-09-07 09:59 UTC, kiview commented on governance/0018-application-process/rfc-18.md
> +* Nods(s) that are implemented after successful application
These are two different points, But having something like `Classes of Membership` sounds reasonable.

2020-09-07 10:08 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
It is the thrid point in the spezifications: * Criteria to evaluate applicants, which would include other points than 3, like contributions to public projects (this also mentioned in the example of Soverin below). Moreover, I wrote in the unresolved questions if there is more criteria that needs to be considered. I thought providing an example is enough since the criteria probably depend strongly on the industry and use case.

2020-09-07 10:10 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +* Nods(s) that are implemented after successful application
the requirements of the node will differ though depending on the classes of membership. Will rephrase it to classes of memberships

2020-09-07 10:14 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
and do we need another rfc for internal voting?

2020-09-11 07:45 UTC, beeshot commented
it would be cool if we can finish this soon? I ask this already twice: Should we do a rfc for internal voting?

2020-09-11 09:04 UTC, kiview requested changes

2020-09-11 09:04 UTC, kiview commented on governance/0018-application-process/README.md
> +>   ** If > 50%of the valid votes areyes, the new member is accepted. If not,the new member is rejected and can reapply at a later time.
```suggestion
>   ** If > 50%of the valid votes are yes, the new member is accepted. If not, the new member is rejected and can reapply at a later time.
```

2020-09-11 09:04 UTC, kiview commented on governance/0018-application-process/README.md
> +A transparent application process flow provides a clear and transparent overview to the applicant and members. It increases confidence that their application has been scrutinized well before a decisi
Please use semantic line breaks, as defined in RFC-0001.

2020-09-11 09:04 UTC, kiview commented on governance/0018-application-process/README.md
> +* Needs to be combined with #0003RFC
Use relative links to reference other RFCs.

2020-09-11 09:04 UTC, kiview commented on governance/0018-application-process/README.md
> +* Workflow process for the organization when applying to join consortial blockchain network.
Process for the applying organization?

2020-09-11 09:04 UTC, kiview commented on governance/0018-application-process/README.md
> +* Nodes(s) that are implemented after successful application
Somehow all open discussions are lost on the PR? 
Nodes are a technical implementation detail, we should not consider here.

2020-09-11 09:04 UTC, kiview commented on governance/0018-application-process/README.md
> +* Voting algorithm including a "majority rule"
Talking about voting here is over-specification.

2020-09-11 09:07 UTC, kiview commented on governance/0018-application-process/rfc-18.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
There could be an RFC for voting, but it should one level more abstract, so decision-making mechanism. However, there might be different decision-making procedures employed for different elements of governance implementation.

So it seems to be sensible to have an abstract RFC `decision-making`, that is used as a primitive/atomic building block in other RFCs.

2020-09-11 09:08 UTC, kiview commented
Maybe ask in the Slack or via Mail to other partners to get more reviewers involved.

2020-09-14 10:49 UTC, fflush reviewed
The current open points would have to be discussed again, especially the matter with the votes. It does not necessarily have to be an election, there are other possibilities. But it should still be formulated differently. Adequate criteria for the admission of new members. Otherwise I think it is good.

2020-09-14 10:49 UTC, fflush commented on governance/0018-application-process/README.md
> +* Nodes(s) that are implemented after successful application
This is not quite clear to me what is actually meant in the context

2020-09-14 10:49 UTC, fflush commented on governance/0018-application-process/README.md
> +* Voting algorithm including a "majority rule"
In principle I think it is not bad if the voting process is addressed but in the form that there should be voting processes.

2020-09-15 13:39 UTC, andionita commented on governance/0018-application-process/README.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
As mentioned before, the summary is identical to the one in governance/0003-Onboarding This RFC is about the application process itself, as far as i understand.

2020-09-15 13:48 UTC, beeshot commented on governance/0018-application-process/README.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
Can you show what is identical? I really don't see it. Plus it says criteria for the application process, which would be e.g. public contributions and are different from what we described in 0003, which are more legal requirements to join.

2020-09-15 13:49 UTC, andionita commented on governance/0018-application-process/README.md
> +* Interval for internal voting process
I would generally replace "voting" with "decision", as it does not have to be through voting that an application is accepted or rejected.

2020-09-15 13:52 UTC, andionita commented on governance/0018-application-process/README.md
> +It increases confidence that their application has been scrutinized well before a decision is made and that only elgibile and trustworthy organizations are able to join.
Also, a process that gives equal chances to all eligible applicants is a good motivation.

2020-09-15 13:55 UTC, andionita commented on governance/0018-application-process/README.md
> +* Classes of Membership
This point is a bit vague. So if there are multiple classes of membership implies that there multiple committees deciding for each? Is this at all relevant for the application process?

2020-09-15 13:57 UTC, beeshot commented on governance/0018-application-process/README.md
> +* Classes of Membership
It means that there are different rights coming with different memberships (before I called it types of nodes that can be operated) than @kiview suggested classed of membership

2020-09-15 14:00 UTC, andionita commented on governance/0018-application-process/README.md
> +* On-chain voting is only pseudonym
Maybe rephrased as the following? In case the decision is met by members on chain, anonymity cannot be assured (pseudonimity at best).

2020-09-15 14:02 UTC, andionita commented on governance/0018-application-process/README.md
> +* Long application process may not seem contemporary for new members
I see what you mean. So in case all members of the network participate in the decision making, it implies a long waiting time.

2020-09-15 14:03 UTC, andionita commented on governance/0018-application-process/README.md
> +* What alternative voting systems could be used?
Is the purpose of this RFC to describe all possible decision making schemes? I rather think not.

2020-09-15 14:11 UTC, andionita requested changes
Some points need to be adjusted, see comments.

2020-09-15 14:14 UTC, andionita commented on governance/0018-application-process/README.md
> +* Classes of Membership
Fine. I guess it is good to have it here but somehow inside a sentence :) Maybe you rephrase your comment a bit and add it.

2020-09-15 14:23 UTC, andionita commented on governance/0018-application-process/README.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
You are right, they are not identical! I totally missed the "application process" part. However, I would skip the "objective criteria" part, as this applies more to the eligibility requirements. Here, it is more about developing a process. It can be mentioned later that objectivity is a property of the process.

2020-10-13 13:37 UTC, beeshot commented on governance/0018-application-process/rfc-18.md
> +The RFC provides the guidelines to develop objective criteria for an application process to select new members to join a consortial blockchain network.
Created an issue for the decision-making RFC

2020-10-14 08:11 UTC, beeshot commented on governance/0018-application-process/README.md
> +* What alternative voting systems could be used?
I don't understand that comment fully :/ I created an RFC0020 called decision-making this could look at the decision-making and voting process in more detail. I think it would make this RFC more lean, understandable, and focused. Not sure if this answers your comment.

2020-10-14 08:12 UTC, beeshot commented on governance/0018-application-process/README.md
> +It increases confidence that their application has been scrutinized well before a decision is made and that only elgibile and trustworthy organizations are able to join.
Also added that

2020-10-14 08:26 UTC, andionita commented on governance/0018-application-process/README.md
> +* What alternative voting systems could be used?
I was commenting on the fact that the unresolved questions are perhaps not relevant for this RFC, as they point to topics outside its scope, i.e. describing alternate voting schemes. But that is just my perception.

2020-10-14 08:29 UTC, beeshot commented on governance/0018-application-process/README.md
> +* What alternative voting systems could be used?
Ahhh I see. Yes, I agree. Deleted them already, Will push the document in a few minutes.

2020-10-16 16:03 UTC, andionita approved these changes
Looks good to me

2020-11-25 11:15 UTC, kiview approved these changes
LGTM

2020-11-25 11:16 UTC, merged